application: guidopercu-1105
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
#root
- url: /
  static_files: frontend/index.html
  upload: frontend/index.html

#serve our home page in case index.html is requested
- url: /index.html
  static_files: frontend/index.html
  upload: frontend/index.html

#all images and support file (css, fonts...): return file if found, 
#otherwise the default 404 page so it can be handled by sites that link
#directly to images.
- url: /(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))
  static_files: frontend/\1
  upload: frontend/(.*\.(gif|png|jpg|ico|bmp|css|otf|eot|svg|ttf|woff))  

#all other urls: return the enkisoftware 404 not found 
#- url: /.*
#  static_files: static_website/notfound.html 
#  upload: static_website/notfound.html

libraries:
- name: webapp2
  version: "2.5.2"
